# Site settings
title: The New Yorker, A Wyndham Hotel | Midtown Manhattan Hotel
email: reservations@nyhotel.com
description: Experience The New Yorker Hotel, a boutique hotel in New York. Book your stay at our Midtown Manhattan Hotel & start your New York getaway.
url: https://www.newyorkerhotel.com
booking_widget_url: https://newyorkerhotel.reztrip.com/mobile

# Build settings
permalink: pretty
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Language settings
default_lang: 'en'
languages: ['en']

data_paginate:
  per_page: 4
  data: 'blog'
  path: 'blog/page:num/'
  pagination_template: 'blog/index.html'
  sort_field: 'date'
  sort_reverse: true

page_gen:
  - data: 'attractions'
    template: 'attraction-details'
    dir: 'attractions'
  - data: 'blog'
    template: 'blog-details'
    dir: 'blog'
  - data: 'category'
    template: 'blog-category'
    dir: 'blog/category'

# File Handling
include:
  - _pages
exclude: [lib, config.rb, .sass-cache, Capfile, config, log, Rakefile, Rakefile.rb, tmp, Gemfile, Gemfile.lock, README.md, LICENSE.md, node_modules, gulpfile.js, package.json, media.json, models.json, sitemap.json]


i18n_dir:
- _ttio_templates/no-bedrock-cp/_locales
- _locales
layouts_dir:
- _ttio_templates/no-bedrock-cp/_layouts
- _layouts
data_dir:
- _ttio_templates/no-bedrock-cp/_data
- _data
includes_dir:
- _includes
- _ttio_templates/no-bedrock-cp/_includes
