 # Site settings
title: The New Yorker, A Wyndham Hotel | Midtown Manhattan Hotel
email: reservations@nyhotel.com
description: > # this means to ignore newlines until "baseurl:"
  Experience The New Yorker Hotel, a boutique hotel in New York. Book your stay at our Midtown Manhattan Hotel & start your New York getaway.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.newyorkerhotel.com/" # the base hostname & protocol for your site

permalink: pretty
default_lang: 'en'
languages: ['en']

exclude: ['sitemap.json']

sass:
  sass_dir: _sass
  style: compressed


booking_widget_url: https://newyorkerhotel.reztrip.com/mobile

data_paginate: 
  per_page: 5
  data: 'blog'
  path: 'blog/page:num'
  pagination_template: 'blog/index.html'
  sort_field: 'date'
  sort_reverse: true

#paginate_path: "/page:num/"
markdown: kramdown 

page_gen:
  - data: 'attractions'
    template: 'attraction-details'
    dir: 'attractions'
  - data: 'blog'
    template: 'blog-details'
    dir: 'blog'